PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT ?symDifference
WHERE {
  my:A geo:hasDefaultGeometry ?aGeom .
  ?aGeom geo:asWKT ?aWKT .
  my:D geo:hasDefaultGeometry ?dGeom .
  ?dGeom geo:asWKT ?dWKT .
  BIND (geof:symDifference(?aWKT, ?dWKT) as ?symDifference)
}
