PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT ?minY
WHERE {
  my:AExactGeom geo:asWKT ?wkt .
  BIND(geof:minY(?wkt) AS ?minY)
}
