PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT (geof:concaveHull(?wkt,"0.99"^^xsd:double) AS ?concavehull)
WHERE {
  ?geom geo:asWKT ?wkt .
}
GROUP BY ?wkt
