PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?relate) as ?relates)
WHERE {
  ?a geo:hasGeometry ?aGeom .
  ?aGeom geo:asWKT ?aWKT .
  ?b geo:hasGeometry ?bGeom .
  ?bGeom geo:asWKT ?bWKT .
  # "T*****FF*" refers to a 'contains' relation in DE-9IM
  BIND (geof:relate(?aWKT, ?bWKT, "T*****FF*"^^xsd:string) as ?relate)
}