prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix geof: <http://www.opengis.net/def/function/geosparql/>
prefix sf: <http://www.opengis.net/ont/sf#>
prefix uom: <http://www.opengis.net/def/uom/OGC/1.0/>
select ?result {
  ?geom1 a sf:LineString;
    geo:asWKT ?result.
  filter(geof:distance(?result, "Point(18.984339 57.430061)"^^geo:wktLiteral, uom:metre) < 500000)
}
order by ?result