PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT ?maxZ
WHERE {
  my:NExactGeom %%literalrel1%% ?%%literal1%% .
  BIND(geof:maxZ(?%%literal1%%) AS ?maxZ)
}
