PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?sfEquals) as ?equals)
WHERE {
  my:I geo:hasDefaultGeometry ?iGeom .
  ?iGeom geo:asKML ?iKML .
  my:H geo:hasDefaultGeometry ?hGeom .
  ?hGeom geo:asKML ?hKML .
  BIND (geof:sfEquals(?iKML, ?hKML) as ?sfEquals)
}
 
