PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?rcc8dc) as ?disconnected)
WHERE {
  my:B geo:hasDefaultGeometry ?bGeom .
  ?bGeom %%literalrel1%% ?b%%literal1%% .
  my:C geo:hasDefaultGeometry ?cGeom .
  ?cGeom %%literalrel2%% ?c%%literal2%% .
  BIND (geof:rcc8dc(?b%%literal1%%, ?c%%literal2%%) as ?rcc8dc)
}
