PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?sfEquals) as ?equals)
WHERE {
  my:L my:hasExactGeometry ?lGeom .
  ?lGeom geo:asKML ?lKML .
  my:M my:hasExactGeometry ?mGeom .
  ?mGeom geo:asWKT ?mWKT .
  BIND (geof:sfEquals(?lKML, ?mWKT) as ?sfEquals)
}
