PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT ?maxY
WHERE {
  my:AExactGeom %%literalrel1%% ?%%literal1%% .
  BIND(geof:maxY(?%%literal1%%) AS ?maxY)
}
