PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?sfCrosses) as ?crosses)
WHERE {
  my:E geo:hasDefaultGeometry ?eGeom .
  ?eGeom %%literalrel1%% ?e%%literal1%% .
  my:A geo:hasDefaultGeometry ?aGeom .
  ?aGeom %%literalrel2%% ?a%%literal2%% .
  BIND (geof:sfCrosses(?e%%literal1%%, ?a%%literal2%%) as ?sfCrosses)
}
