PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT (geof:concatLines(?%%literal1%%) AS ?concatlines)
WHERE {
  ?geom %%literalrel1%% ?%%literal1%% .
}
GROUP BY ?%%literal1%%
