PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
SELECT ?wkt (CONCAT_LINES(?geom AS ?concatlines))
WHERE {
  ?geom geo:asWKT ?wkt .
}
GROUP BY ?wkt