PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
SELECT ?wkt (CONCAVEHULL(?geom AS ?concavehull))
WHERE {
  ?geom geo:asWKT ?wkt .
}
GROUP BY ?wkt