PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?sfEquals) as ?equals)
WHERE {
  my:I geo:hasDefaultGeometry ?iGeom .
  ?iGeom geo:asGeoJSON ?iGeoJSON .
  my:H geo:hasDefaultGeometry ?hGeom .
  ?hGeom geo:asGeoJSON ?hGeoJSON .
  BIND (geof:sfEquals(?iGeoJSON, ?hGeoJSON) as ?sfEquals)
}