PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?rcc8tppi) as ?tangentialProperPartInverse)
WHERE {
  my:A geo:hasDefaultGeometry ?aGeom .
  ?aGeom geo:asGML ?aGML .
  my:B geo:hasDefaultGeometry ?bGeom .
  ?bGeom geo:asGML ?bGML .
  BIND (geof:rcc8tppi(?aGML, ?bGML) as ?rcc8tppi)
}
