PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT xsd:boolean(?rcc8ec) as ?externallyConnected
WHERE {
  my:A geo:hasDefaultGeometry ?aGeom .
  ?aGeom geo:asWKT ?aWKT .
  my:C geo:hasDefaultGeometry ?cGeom .
  ?cGeom geo:asWKT ?cWKT .
  BIND (geof:rcc8ec(?aWKT, ?cWKT) as ?rcc8ec)
}
