PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT xsd:boolean(?rcc8tpp) as ?tangentialProperPart
WHERE {
  my:B geo:hasDefaultGeometry ?bGeom .
  ?bGeom geo:asWKT ?bWKT .
  my:A geo:hasDefaultGeometry ?aGeom .
  ?aGeom geo:asWKT ?aWKT .
  BIND (geof:rcc8tpp(?bWKT, ?aWKT) as ?rcc8tpp)
}
