PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?ehDisjoint) as ?disjoint)
WHERE {
  my:B geo:hasDefaultGeometry ?bGeom .
  ?bGeom geo:asWKT ?bWKT .
  my:C geo:hasDefaultGeometry ?cGeom .
  ?cGeom geo:asGML ?cGML .
  BIND (geof:ehDisjoint(?bWKT, ?cGML) as ?ehDisjoint)
}
