PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT xsd:boolean(?sfEquals) as ?equals
WHERE {
  my:I my:hasPointGeometry ?iGeom .
  ?iGeom geo:asGML ?iGML .
  my:H my:hasPointGeometry ?hGeom .
  ?hGeom geo:asGML ?hGML .
  BIND (geof:sfEquals(?iGML, ?hGML) as ?sfEquals)
}
