PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT xsd:boolean(?ehDisjoint) as ?disjoint
WHERE {
  my:B geo:hasDefaultGeometry ?bGeom .
  ?bGeom geo:asWKT ?bWKT .
  my:C geo:hasDefaultGeometry ?cGeom .
  ?cGeom geo:asWKT ?cWKT .
  BIND (geof:ehDisjoint(?bWKT, ?cWKT) as ?ehDisjoint)
}
