PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?rcc8eq) as ?equals)
WHERE {
  my:A geo:hasDefaultGeometry ?aGeom .
  ?aGeom geo:asWKT ?aWKT .
  my:B geo:hasDefaultGeometry ?bGeom .
  ?bGeom geo:asWKT ?bWKT .
  BIND (geof:rcc8eq(?aWKT, ?bWKT) as ?rcc8eq)
}
