PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?sfDisjoint) as ?disjoint)
WHERE {
  my:C geo:hasDefaultGeometry ?cGeom .
  ?cGeom %%literalrel1%% ?c%%literal1%% .
  my:F geo:hasDefaultGeometry ?fGeom .
  ?fGeom %%literalrel2%% ?f%%literal2%% .
  BIND (geof:sfDisjoint(?c%%literal1%%, ?f%%literal2%%) as ?sfDisjoint)
}
