PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
SELECT (BBOX(?%%literal1%%) AS ?bbox)
WHERE {
  ?geom %%literalrel1%% ?%%literal1%% .
}
GROUP BY ?%%literal1%%
