PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?sfDisjoint) as ?disjoint)
WHERE {
  my:C geo:hasDefaultGeometry ?cGeom .
  ?cGeom geo:asWKT ?cWKT .
  my:F geo:hasDefaultGeometry ?fGeom .
  ?fGeom geo:asWKT ?fWKT .
  BIND (geof:sfDisjoint(?cWKT, ?fWKT) as ?sfDisjoint)
}
