PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT ?srid
WHERE {
  my:A geo:hasDefaultGeometry ?geom .
  ?geom geo:asGML ?gml .
  BIND (geof:getSRID(?gml) as ?srid)
}
