PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?rcc8ntpp) as ?nonTangentialProperPart)
WHERE {
  my:G geo:hasDefaultGeometry ?gGeom .
  ?gGeom geo:asWKT ?gWKT .
  my:A geo:hasDefaultGeometry ?aGeom .
  ?aGeom geo:asWKT ?aWKT .
  BIND (geof:rcc8ntpp(?gWKT, ?aWKT) as ?rcc8ntpp)
}
