PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:boolean(?sfOverlaps) as ?overlaps)
WHERE {
  my:A geo:hasDefaultGeometry ?aGeom .
  ?aGeom geo:asGML ?aGML .
  my:D geo:hasDefaultGeometry ?dGeom .
  ?dGeom geo:asGML ?dGML .
  BIND (geof:sfOverlaps(?aGML, ?dGML) as ?sfOverlaps)
}
