PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT ?symDifference
WHERE {
  my:A geo:hasDefaultGeometry ?aGeom .
  ?aGeom geo:asGML ?aGML .
  my:D geo:hasDefaultGeometry ?dGeom .
  ?dGeom geo:asGML ?dGML .
  BIND (geof:symDifference(?aGML, ?dGML) as ?symDifference)
}
