PREFIX my: <http://example.org/ApplicationSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT ?envelope
WHERE {
  my:A geo:hasDefaultGeometry ?geom .
  ?geom geo:asGML ?gml .
  BIND (geof:envelope(?gml) as ?envelope)
}
